// Simulated Admin Portal Seed Data for Assignments
// 10+ assignments across 1.5 years (past 6 months + next 12 months)

export const SEED_COURSES = [
  'CS302: Data Structures & Algorithms',
  'MAT201: Calculus III',
  'ENG101: Creative Writing',
  'PHY101: Introduction to Physics',
  'CS402: Human Computer Interaction',
  'MKT310: Digital Marketing',
  'ART105: Modern Visual Design',
  'SEM001: Research Methods',
];

// Helper: date string relative to today
const relativeDate = (daysFromNow, timeStr = '11:59 PM') => {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }) + ', ' + timeStr;
};

export const SEED_ASSIGNMENTS = [
  // ── Past (Completed) Assignments ──────────────────────────────
  {
    id: 'seed-1',
    status: 'Completed',
    course: 'CS302: Data Structures & Algorithms',
    title: 'Lab 1: Linked List Implementation',
    desc: 'Implement a singly linked list in C++ with insert, delete, and search operations. Include time complexity analysis.',
    due: relativeDate(-120, '11:59 PM'),
    meta: 'Solo Submission',
    metaIcon: 'person',
    completed: true,
    submissions: [],
  },
  {
    id: 'seed-2',
    status: 'Completed',
    course: 'MAT201: Calculus III',
    title: 'Problem Set 1: Partial Derivatives',
    desc: 'Solve problems 1–20 from Chapter 13. Show all working and verify answers using second derivative test.',
    due: relativeDate(-90, '5:00 PM'),
    meta: 'Handwritten Allowed',
    metaIcon: 'edit_note',
    completed: true,
    submissions: [],
  },
  {
    id: 'seed-3',
    status: 'Completed',
    course: 'ENG101: Creative Writing',
    title: 'Short Story Draft — 1500 Words',
    desc: 'Write a short story of 1500 words using the narrative technique discussed in Week 4. Submit as a PDF.',
    due: relativeDate(-60, '11:59 PM'),
    meta: 'PDF Submission',
    metaIcon: 'picture_as_pdf',
    completed: true,
    submissions: [],
  },
  {
    id: 'seed-4',
    status: 'Completed',
    course: 'PHY101: Introduction to Physics',
    title: 'Lab Report: Newton\'s Laws Experiment',
    desc: 'Document results from the friction and inclined plane lab. Include data tables, graphs, and error analysis.',
    due: relativeDate(-45, '11:59 PM'),
    meta: 'Lab Submission',
    metaIcon: 'science',
    completed: true,
    submissions: [],
  },

  // ── Active / Upcoming Assignments ─────────────────────────────
  {
    id: 'seed-5',
    status: 'Urgent',
    course: 'CS302: Data Structures & Algorithms',
    title: 'Assignment 3: Binary Search Tree',
    desc: 'Implement a BST with insert, delete, inorder traversal, and level-order traversal. Analyse worst-case time complexity.',
    due: relativeDate(2, '11:59 PM'),
    meta: '3 Resources',
    metaIcon: 'attach_file',
    completed: false,
    submissions: [],
  },
  {
    id: 'seed-6',
    status: 'Urgent',
    course: 'MAT201: Calculus III',
    title: 'Problem Set 8: Triple Integrals',
    desc: 'Focus on spherical and cylindrical coordinate conversions. Must show work for all even-numbered problems in Chapter 14.4.',
    due: relativeDate(4, '5:00 PM'),
    meta: 'Group Allowed',
    metaIcon: 'group',
    completed: false,
    submissions: [],
  },
  {
    id: 'seed-7',
    status: 'In Progress',
    course: 'CS402: Human Computer Interaction',
    title: 'Project Milestone 2: Prototype & User Testing',
    desc: 'Build a medium-fidelity prototype on Figma and conduct user testing with at least 5 participants. Submit a 3-page report.',
    due: relativeDate(10, '11:59 PM'),
    meta: 'Group of 3',
    metaIcon: 'group',
    completed: false,
    submissions: [],
  },
  {
    id: 'seed-8',
    status: 'In Progress',
    course: 'MKT310: Digital Marketing',
    title: 'Social Media Campaign Analysis',
    desc: 'Analyse a real-world social media campaign (brand of your choice). Evaluate reach, engagement, and ROI. Min 2000 words.',
    due: relativeDate(14, '11:59 PM'),
    meta: 'PDF + Slides',
    metaIcon: 'slideshow',
    completed: false,
    submissions: [],
  },
  {
    id: 'seed-9',
    status: 'Planned',
    course: 'PHY101: Introduction to Physics',
    title: 'Lab Report: Wave Interference Patterns',
    desc: 'Summarise findings from the double-slit experiment lab. Include intensity graphs and wavelength calculations.',
    due: relativeDate(21, '11:59 PM'),
    meta: 'Lab Submission',
    metaIcon: 'science',
    completed: false,
    submissions: [],
  },
  {
    id: 'seed-10',
    status: 'Planned',
    course: 'ART105: Modern Visual Design',
    title: 'Design Portfolio — Module 2',
    desc: 'Submit a digital portfolio of 5 original design works created during Module 2. Include a 300-word artist statement.',
    due: relativeDate(28, '11:59 PM'),
    meta: 'Digital Portfolio',
    metaIcon: 'brush',
    completed: false,
    submissions: [],
  },
  {
    id: 'seed-11',
    status: 'Planned',
    course: 'SEM001: Research Methods',
    title: 'Literature Review — 2500 Words',
    desc: 'Write a structured literature review on your chosen research topic. Cite at least 15 peer-reviewed sources in APA format.',
    due: relativeDate(35, '11:59 PM'),
    meta: 'Turnitin Required',
    metaIcon: 'verified',
    completed: false,
    submissions: [],
  },
  {
    id: 'seed-12',
    status: 'Planned',
    course: 'ENG101: Creative Writing',
    title: 'Final Short Story — Revised Draft',
    desc: 'Revise your Week 4 short story based on peer feedback. Final submission must be 2000–2500 words with a reflection note.',
    due: relativeDate(42, '11:59 PM'),
    meta: 'PDF Submission',
    metaIcon: 'picture_as_pdf',
    completed: false,
    submissions: [],
  },
  {
    id: 'seed-13',
    status: 'Planned',
    course: 'CS302: Data Structures & Algorithms',
    title: 'Final Project: Graph Algorithms Visualiser',
    desc: 'Build a web-based visualiser for BFS, DFS, Dijkstra, and A* algorithms. Must include step-by-step animation and a written report.',
    due: relativeDate(60, '11:59 PM'),
    meta: 'Solo / Pair',
    metaIcon: 'code',
    completed: false,
    submissions: [],
  },
];
